version: '3.8'

services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command: serve --dev-addr=0.0.0.0:8000 --livereload
    restart: unless-stopped
